# Generated by Django 5.1.1 on 2024-10-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_sellorder_order_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellorder',
            old_name='total_amount',
            new_name='total_cost',
        ),
    ]
