# Generated by Django 5.1.1 on 2024-10-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_rename_total_amount_sellorder_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorders_detail',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sellorder_detail',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
