# Generated by Django 5.1.1 on 2024-10-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
